title: Aqsa Ajaz # your name (or website title) here
logo: "/images/AQSA.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A qualified and experienced Researcher/Analyst with over 4 years’(research) experience in interpreting and analysing data to draw meaningful insights. 
  <br><br>
  Skilled in various data analysing and visualisation software's SQL, Python, Excel, Tableau, Power BI and SPSS.
  <br><br>
  <a href="https://www.linkedin.com/in/aqsa-ajaz-77727b2a">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

